name: Coding Assignment 13

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier:check

      - name: Run ESLint check
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build and deploy
        run: |
          npm run build
          docker build -t bergen_savanna_coding_assignment13 .
          docker run -p 8018:8018 bergen_savanna_coding_assignment13
